#!/bin/bash

if [ -z "$1" ]; then
  cargo watch -x 'test --message-format json-diagnostic-rendered-ansi | quiet --errors 1'
else
  cargo watch -x 'test '"$1"' --message-format json-diagnostic-rendered-ansi | quiet --errors 1'
fi


