#!/bin/bash

if [ -z "$1" ]; then
  cargo watch -x 'test -q --message-format json-diagnostic-rendered-ansi | quiet --errors 1'
else
  cargo watch -x 'test '"$1"' -q --message-format json-diagnostic-rendered-ansi | quiet --errors 1'
fi


