pub mod file_chooser;
pub mod token_replacer;
pub mod file_traverser;
pub mod template_enricher;
pub mod process_templates;
pub mod default_process_templates;
pub mod enriched_template_file_processor;
pub mod file_writer;
pub mod directory_creator;
pub mod string_token_replacer;

mod regex_file_chooser;
mod default_template_enricher;
mod walk_dir_file_traverser;
mod aho_corasick_token_replacer;
mod default_file_writer;
mod enriched_default_template_file_processor;
mod default_directory_creator;
mod source_file;
mod destination_file;
