name: linux
on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: (${{ matrix.target }}-${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        target: [
          x86_64-unknown-linux-gnu,
        ]

    steps:
    - name: Checkout Zat
      uses: actions/checkout@v4

      # Run build
    - name: Install rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
        sh rustup-init.sh -y --default-toolchain none
        rustup target add ${{ matrix.target }}

    - name: Build
      run: |
        rustc -Vv
        cargo -V
        cargo build

    - name: Run Tests
      run: cargo test
