name: mac release
on:
  push:
    branches:
      - "fix-release-targets"

  # push:
    # tags:
      # - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    name: (${{ matrix.target }}-${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-13]
        target: [
          x86_64-apple-darwin,
          aarch64-apple-darwin,
        ]

    steps:
    - name: checkout
      uses: actions/checkout@v4

      # Run build
    - name: install rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
        sh rustup-init.sh -y --default-toolchain none
        rustup target add ${{ matrix.target }}
    - name: build
      id: release-build
      run: |
        rustc -Vv
        cargo -V
        cargo build --release --target {{ matrix.target }}
        ZAT_VERSION=$(target/release/zat -V | cut -d' ' -f2)
        echo "ARTIFACT_NAME=target/release/zat" >> "$GITHUB_ENV"
        echo "RELEASE_ARTIFACT_NAME=target/release/zat-$ZAT_VERSION-${{ matrix.os }}-${{ matrix.target }}" >> "$GITHUB_ENV"

    # - name: copy-artifact
    #   id: copy-artifact
    #   run: |
    #     echo "RELEASE_ARTIFACT_NAME: $RELEASE_ARTIFACT_NAME"
    #     echo "ARTIFACT_NAME: $ARTIFACT_NAME"
    #     cp "$ARTIFACT_NAME" "$RELEASE_ARTIFACT_NAME"

    # - uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     files: ${{ env.RELEASE_ARTIFACT_NAME }}
