name: mac release
on:
  push:
    branches:
      - "fix-release-targets"

  # push:
    # tags:
      # - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    name: (${{ matrix.target }}-${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13]
        target: [
          x86_64-apple-darwin
        ]

    steps:
    - name: Checkout zat
      uses: actions/checkout@v4
      with:
        path: zat

    - name: Checkout homebrew-zat
      uses: actions/checkout@v4
      with:
        repository: ssanj/homebrew-zat
        path: homebrew-zat

    - name: Echo Paths
      run: |
        echo "$PWD:"
        ls -l "$PWD"

      # Run build
    - name: install rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
        sh rustup-init.sh -y --default-toolchain none
        rustup target add ${{ matrix.target }}

    - name: build
      id: release-build
      run: |
        rustc -Vv
        cargo -V
        ZAT_DIR="$PWD/zat"
        cd "$ZAT_DIR"
        cargo build --release --target ${{ matrix.target }} --target-dir "$ZAT_DIR/target"
        RELEASE_DIR="$ZAT_DIR/target/${{ matrix.target }}/release"
        RELEASE_EXEC="$RELEASE_DIR/zat"
        echo "RELEASE_DIR: $RELEASE_DIR"
        echo "RELEASE_EXEC: $RELEASE_EXEC"
        # ZAT_VERSION=$($RELEASE_EXEC -V | cut -d' ' -f2)
        # TODO: Fix to use actual version
        # ZAT_VERSION="0.11.10"
        echo "ZAT_VERSION=$ZAT_VERSION" >> "$GITHUB_ENV"
        echo "ARTIFACT_NAME=$RELEASE_EXEC" >> "$GITHUB_ENV"
        echo "RELEASE_ARTIFACT_NAME=$RELEASE_EXEC-$ZAT_VERSION-${{ matrix.os }}-${{ matrix.target }}" >> "$GITHUB_ENV"

    - name: copy-artifact
      id: copy-artifact
      run: |
        echo "RELEASE_ARTIFACT_NAME: $RELEASE_ARTIFACT_NAME"
        echo "ARTIFACT_NAME: $ARTIFACT_NAME"
        cp "$ARTIFACT_NAME" "$RELEASE_ARTIFACT_NAME"

    # - uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     files: ${{ env.RELEASE_ARTIFACT_NAME }}

    - name: Echo Parts
      run: |
        echo "ZAT_VERSION: $ZAT_VERSION"
        echo "PWD: $PWD"

    - name: Download new source
      run: |
        curl -L -o "$ZAT_VERSION.tar.gz" "https://github.com/ssanj/zat/archive/refs/tags/v$ZAT_VERSION.tar.gz"
        ZAT_SHA256=$(openssl sha256 < "$ZAT_VERSION.tar.gz")
        echo "ZAT_SHA256: $ZAT_SHA256"

    # - name: Generate Homebrew Formula
    #   uses: cuchi/jinja2-action@v1.2.2
    #   with:
    #     template: infra/nginx.conf.j2
    #     output_file: infra/nginx.conf
    #     strict: true
    #     variables: |
    #       ZAT_VERSION=$ZAT_VERSION
    #       timeout=30s



