name: mac release
on:
  push:
    # tags:
    #   - "v*"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: (${{ matrix.target }}-${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-13]
        target: [
          x86_64-apple-darwin,
          aarch64-apple-darwin,
        ]

    steps:
    - name: checkout
      uses: actions/checkout@v2

      # Run build
    - name: install rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
        sh rustup-init.sh -y --default-toolchain none
        rustup target add ${{ matrix.target }}
    - name: build
      id: release-build
      run: |
        rustc -Vv
        cargo -V
        cargo build --release
        echo "::set-output name=release-artifact-name::target/release/zat"

    - name: copy-artifact
      id: copy-artifact
      run: |
        cp "${{ steps.release-build.outputs.release-artifact-name }}" "$ARTIFACT_NAME"
        echo "::set-output name=artifact-name::$ARTIFACT_NAME"
      env:
        ARTIFACT_NAME: "${{ steps.release-build.outputs.release-artifact-name }}-${{ matrix.os }}-{{ matrix.target }}"

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: "${{ steps.copy-artifact.outputs.artifact-name }}"
